version: '3.4'

services:
  demo:
    image: demo
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
  redis:
    image: "redis:alpine"
    ports:
      - 6379
